; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.39"

; Modules
projects[configuration][subdir] = "contrib"
projects[configuration][version] = "2.0-alpha3"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[features][subdir] = "contrib"
projects[features][version] = "2.6"

projects[xautoload][subdir] = "contrib"
projects[xautoload][version] = "5.5"

