; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.39"

; Modules
projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc5"

projects[admin_language][subdir] = "contrib"
projects[admin_language][version] = "1.0-beta1"

projects[adminimal_admin_menu][subdir] = "contrib"
projects[adminimal_admin_menu][version] = "1.6"

projects[audiofield][subdir] = "contrib"
projects[audiofield][version] = "1.0"

projects[avatar_selection][subdir] = "contrib"
projects[avatar_selection][version] = "1.1"

projects[block_class][subdir] = "contrib"
projects[block_class][version] = "2.1"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.9"

projects[ckeditor][subdir] = "contrib"
projects[ckeditor][version] = "1.16"

projects[configuration][subdir] = "contrib"
projects[configuration][version] = "2.0-alpha3"

projects[date][subdir] = "contrib"
projects[date][version] = "2.9"

projects[diff][subdir] = "contrib"
projects[diff][version] = "3.2"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.6"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.1"

projects[entityreference_prepopulate][subdir] = "contrib"
projects[entityreference_prepopulate][version] = "1.5"

projects[features][subdir] = "contrib"
projects[features][version] = "2.6"

projects[file_entity][subdir] = "contrib"
projects[file_entity][version] = "2.0-beta2"

projects[flag][subdir] = "contrib"
projects[flag][version] = "3.6"

projects[i18n][subdir] = "contrib"
projects[i18n][version] = "1.13"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.5"

projects[image_field_caption][subdir] = "contrib"
projects[image_field_caption][version] = "2.1"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "3.0-alpha2"

projects[media][subdir] = "contrib"
projects[media][version] = "2.0-beta1"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "2.0"

projects[multiple_registration][subdir] = "contrib"
projects[multiple_registration][version] = "1.0"

projects[panels_bootstrap_layouts][subdir] = "contrib"
projects[panels_bootstrap_layouts][version] = "3.0"

projects[panels_bootstrap_styles][subdir] = "contrib"
projects[panels_bootstrap_styles][version] = "1.0-alpha1"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.3"

projects[prepopulate][subdir] = "contrib"
projects[prepopulate][version] = "2.0"

projects[profile2][subdir] = "contrib"
projects[profile2][version] = "1.3"

projects[rules][subdir] = "contrib"
projects[rules][version] = "2.9"

projects[rules_conditional][subdir] = "contrib"
projects[rules_conditional][version] = "1.0-beta2"

projects[session_api][subdir] = "contrib"
projects[session_api][version] = "1.0-rc1"

projects[token][subdir] = "contrib"
projects[token][version] = "1.6"

projects[translation_helpers][subdir] = "contrib"
projects[translation_helpers][version] = "1.0"

projects[transliteration][subdir] = "contrib"
projects[transliteration][version] = "3.2"

projects[variable][subdir] = "contrib"
projects[variable][version] = "2.5"

projects[video_embed_field][subdir] = "contrib"
projects[video_embed_field][version] = "2.0-beta11"

projects[views][subdir] = "contrib"
projects[views][version] = "3.11"

projects[views_bootstrap][subdir] = "contrib"
projects[views_bootstrap][version] = "3.1"

projects[views_maintenance][subdir] = "contrib"
projects[views_maintenance][version] = "1.1"

projects[xautoload][subdir] = "contrib"
projects[xautoload][version] = "5.5"

; Themes
projects[adminimal_theme][version] = "1.22"

projects[bootstrap][version] = "3.0"

